# To start both nodejs and mongodb simultaneously

version: '3.9'

# Services to start
services:
  # MongoDB
  mongoDb: 
    image: mongo:latest
    restart: always
    volumes:
      - mongoDb:/data/db
    
  api: 
    build: .
    ports: 
      - 3000:3000
    
volumes:
  mongoDb: {}